# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:            [jekyll-paginate, jemoji]

# Permalinks
permalink:        pretty

# Setup
title:            Eat a Bit of Pi
tagline:          'Saurabh Batra'
description:      'Open source chronicles and personal blog of <a href="https://www.facebook.com/saurabhbatra" target="_blank">Saurabh Batra</a>; complete with a clich&#232;d punny title and all.'
url:              http://saurabhbatra96.github.io
baseurl:          

# Hyde theme author

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


excerpt_separator: <!--more-->
